sudo: false
language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"
  - "pypy3"
# Travis will clone only 50 commits by default. This project however uses the
# number of commits to determine the version number. Hence we need ALL the
# commits. This will make the lone unshallow.
before_install:
  - git fetch --unshallow
install:
  # Temporary workaround for https://github.com/pybuilder/pybuilder/issues/310
  - pip install pybuilder!=0.11.3 coveralls
  - pyb -v install_dependencies

script:
  - pyb -v -X verify analyze
after_success:
  - coveralls --verbose
before_deploy:
  - pyb -v -X package
deploy:
  provider: pypi
  user: Immobilienscout24
  distributions: "sdist"
  skip_cleanup: true
  password:
    secure: dBFPABJ+Be1JsdcOlpdzGKxU1NpH5j3mnfPxWqguMqpHHTqHmPYV4ruFKX0bt7n5XGlJy5/T4WW5W4xh0jUrKuMHVEZhgzlmPLyOzrfZXFFJdE3VVviLKhND0JRUocMK7xADsAZlcfnfCw+ydlEtjI4+8mKwGH2mxelm9Zf1f8JemOuyyKux/Aqxo8vcSJgUBKgfdGf0a5TWMXCxuGRnnP2mpgZwtyfqJSaz+BvO82sXCKG0jdMw+NqL6io8xnIpdjoKhe9NwDWe0A2G0lbC6W8DnHH5kkqvPQUNjL6iX+JACxefFI6JUgPB1vG8S4WAbacedE5e9UWl+aJqrtLeOU+JnvByOmMAH1tM91i+gF/zC8ew68DCUc+FD4GnMLyFrALeoiItDU5jhFXO4Rrf9RscOa1ftw/QVZaPatfjMlf6ggh9yZVK4HZXuQtk41kjbvhE7TWjBM580UD5TiMjwbGBHN+lgEPOXDCzwTwJGiMvzLE8cJ1ZZiYfH6PyS+1HBV9zUYw6C4j0/pATObrx8mqQjf1Gyp36UC+7lr7mPh40PqZEH788AHFwm30aSKNmDIOvMwAXOb0h8z1AUUWvpKtB2PLQ84cjuOvrxokut4KRrUwp5mx2UMpiYZpSad64N9dPkehdn3JNyedMQ+iRvM9hh7ari78ywfPE6bFQCk8=
  on:
    repo: ImmobilienScout24/pybuilder_aws_plugin
    python: '3.5'
    branch: master
